### ISSUE TITLE
/github/: IT'S MINE

### ISSUE THREAD

**Issue by bawjensen** [WheatonWHALE/whaleweb#85]
Posted by Real 1'st Place:

I don't think any more info is needed.. GitHub needs to make private contributions publicly noticed haha

- Clayton

**Comment by cjrieck** [comment]
Oh crap, if I knew my comment would be parsed as markdown I would've added some crazy stuff in haha

**Comment by bawjensen** [comment]
Haha, but if private contributions are shown, then are they really private? O.o

**Comment by bawjensen** [comment]
The thing is, I could set up a system for authentication, and maybe parse people's site page as if they're signed in. But that's so much more complicated than the current setup of a few HTML get requests.

**Comment by bawjensen** [comment]
What're you at, privately?
